/**
 * \file       SchM_Fee.h
 * \brief      BSW Scheduler (SchM) Declarations for Fee Module
 *
 * \details    Provides exclusive area enter/exit declarations for the
 *             Fee module. For host unit-test builds (FEE_UNIT_TEST defined),
 *             these expand to empty macros.
 *
 *             <PLACEHOLDER_REQUIRED> Implementation generated by
 *             RTE/SchM generator.
 *
 * \copyright  Copyright (c) 2024 -- All rights reserved.
 *             AUTOSAR R24-11 compliant.
 *
 * \autosar    AUTOSAR_SWS_BSWScheduler
 * \version    24.11.0
 */

#ifndef SCHM_FEE_H
#define SCHM_FEE_H

#ifdef FEE_UNIT_TEST

/*============================================================================*
 *  Unit-test mode: exclusive areas expand to nothing
 *============================================================================*/

/** \brief Enter exclusive area 0 (empty for host builds) */
#define SchM_Enter_Fee_FEE_EXCLUSIVE_AREA_0()   do { } while(0)

/** \brief Exit exclusive area 0 (empty for host builds) */
#define SchM_Exit_Fee_FEE_EXCLUSIVE_AREA_0()    do { } while(0)

#else /* !FEE_UNIT_TEST */

/*============================================================================*
 *  Production mode: function declarations
 *  <PLACEHOLDER_REQUIRED> Implementation generated by RTE/SchM generator.
 *============================================================================*/

#include "Std_Types.h"

/**
 * \brief  Enter Fee exclusive area 0
 * \details Disables interrupts or acquires spinlock as configured
 */
extern FUNC(void, FEE_CODE) SchM_Enter_Fee_FEE_EXCLUSIVE_AREA_0(void);

/**
 * \brief  Exit Fee exclusive area 0
 * \details Re-enables interrupts or releases spinlock as configured
 */
extern FUNC(void, FEE_CODE) SchM_Exit_Fee_FEE_EXCLUSIVE_AREA_0(void);

#endif /* FEE_UNIT_TEST */

#endif /* SCHM_FEE_H */
